DROP TABLE BREED;

CREATE TABLE BREED(
	BreedName					NVARCHAR(25)	NOT NULL,
	MinWeight					FLOAT			NULL,
	MaxWeight					FLOAT			NULL,
	AverageLifeExpectancy		INT				NULL,
	CONSTRAINT					BREED_PK		PRIMARY KEY(BreedName)
	);

ALTER TABLE PET
	ADD CONSTRAINT BREED_FK	FOREIGN KEY (PetBreed)
			REFERENCES BREED(BreedName)

INSERT INTO BREED VALUES ('Border Collie', 15.0, 22.5, 20);
INSERT INTO BREED VALUES ('Cashmere', 10.0, 15.0, 12);
INSERT INTO BREED VALUES ('Collie Mix', 17.5, 25.0, 18);
INSERT INTO BREED VALUES ('Std. Poodle', 22.5, 30.0, 18);
INSERT INTO BREED (BreedName)
VALUES ('Unknown');